<?php
$c=isset($_GET['id'])?activeClient(positiveId($_GET['id'])):null;
$techs=sql('SELECT * FROM technicians WHERE deletedAt IS NULL ORDER BY nome')->fetchAll();
$selected=$c?array_column(sql('SELECT technicianId FROM client_technicians WHERE clientId=?',[$c['id']])->fetchAll(),'technicianId'):[];
if(is_array($_POST['technicians']??null))$selected=$_POST['technicians'];
?>
<a href="<?=$c?'?client='.(int)$c['id']:'index.php'?>" class="back-link"><?=icon('arrow')?> Voltar</a><div class="page-heading"><div><span class="eyebrow">CARTEIRA DE CLIENTES</span><h1><?=$c?'Editar acompanhamento':'Novo cliente'?></h1><p>Defina quem acompanha e qual será o próximo passo.</p></div></div>
<section class="panel form-panel"><form method="post" class="form-stack"><?php formAction('client_save',$c);?><div class="form-grid"><label>Nome do cliente<input name="nome" required maxlength="160" value="<?=h(postVal('nome',$c['nome']??''))?>"></label><label>Responsável do CS<select name="ownerId"><?php userOptions($users,postVal('ownerId',$c['ownerId']??''));?></select></label><label>Status<select name="status"><?php options(statusLabels(),postVal('status',$c?clientStage($c):defaultStage()));?></select></label><label>Prioridade<select name="priority"><?php options(PRIORITIES,postVal('priority',$c['priority']??'normal'));?></select></label><label>Próximo contato<input type="date" name="nextContact" value="<?=h(postVal('nextContact',$c['nextContact']??''))?>"></label><label>Frequência de contato (dias)<input type="number" name="cadence" min="1" max="365" required value="<?=h(postVal('cadence',$c['cadence']??7))?>"><small>Alertas crescentes em 60% e 85% do intervalo; após o prazo, urgente.</small></label></div><label>Descrição do acompanhamento<textarea name="observacoes" rows="7" maxlength="15000" placeholder="Contexto do cliente, objetivos e informações importantes para a equipe."><?=h(postVal('observacoes',$c['observacoes']??''))?></textarea></label>
<?php
$newRows=is_array($_POST['newTechnicians']??null)?array_values($_POST['newTechnicians']):[[]];
?><fieldset class="client-technicians"><legend>Contatos do cliente</legend><p class="muted">Selecione contatos já cadastrados ou adicione novos contatos deste cliente. Eles não recebem acesso ao sistema.</p>
<input type="hidden" name="newTechnicianCount" id="new-technician-count" value="<?=count($newRows)?>">
<label>Buscar contato existente<input type="search" id="technician-search" placeholder="Digite o nome do contato" autocomplete="off"></label>
<div class="technician-picker"><?php foreach($techs as $t):?><div class="technician-option" data-name="<?=h($t['nome'])?>"><label><input type="checkbox" name="technicians[]" value="<?=(int)$t['id']?>" <?=in_array($t['id'],$selected)?'checked':''?>><span><strong><?=h($t['nome'])?></strong><small><?=h(implode(' · ',array_filter([$t['whatsapp']?'+'.$t['whatsapp']:'',$t['email']])))?></small></span></label></div><?php endforeach;?></div>
<p class="muted" id="technician-search-empty" <?=$techs?'hidden':''?>>Nenhum contato encontrado. Cadastre um abaixo.</p><p class="muted" id="technician-selected-count" aria-live="polite"></p>
<div id="new-technicians"><?php foreach($newRows as $key=>$values)if(is_array($values))newTechnicianRow((string)$key,$values);?></div><button type="button" class="button secondary" id="add-technician"><?=icon('plus')?> Adicionar outro contato</button><small class="contact-help">WhatsApp brasileiro: informe DDD e número. Para outros países, use + e o código do país. Os novos contatos serão salvos e vinculados junto com o cliente.</small>
<template id="technician-template"><?php newTechnicianRow('__KEY__');?></template></fieldset><div class="form-actions"><button class="button primary">Salvar acompanhamento</button><a class="button secondary" href="<?=$c?'?client='.(int)$c['id']:'index.php'?>">Cancelar</a></div></form></section>
