<?php
$archived=($_GET['archived']??'')==='1';$rows=clientRows($archived);
$q=is_string($_GET['q']??null)?trim($_GET['q']):'';$layout=in_array($_GET['layout']??'list',['list','cards','board'],true)?($_GET['layout']??'list'):'list';
$filter=is_string($_GET['filter']??null)?$_GET['filter']:'';$owner=is_string($_GET['owner']??null)?$_GET['owner']:'';$sort=($_GET['sort']??'oldest');
$allCount=count($rows);$stale=count(array_filter($rows,'contactLate'));$lateCount=count(array_filter($rows,fn($c)=>$c['status']!=='done'&&late($c['nextContact'])));
$mine=(int)sql('SELECT COUNT(*) FROM tasks t JOIN clients c ON c.id=t.clientId WHERE t.assigneeId=? AND t.completedAt IS NULL AND t.deletedAt IS NULL AND c.deletedAt IS NULL',[$user['id']])->fetchColumn();
$rows=array_values(array_filter($rows,function($c)use($q,$filter,$owner){
 if($q!=='' && !((preg_match('/^[0-9]+$/D',$q)===1&&(int)$q===(int)$c['id'])||preg_match('/'.preg_quote($q,'/').'/iu',$c['nome'])===1))return false;
 if($owner!==''&&(int)$owner!==(int)$c['ownerId'])return false;
 if($filter==='late')return contactLate($c);
 if($filter==='due')return $c['status']!=='done'&&late($c['nextContact']);
 return !$filter||clientStage($c)===$filter;
}));
if($sort==='updated')usort($rows,fn($a,$b)=>strcmp($b['updatedAt'],$a['updatedAt'])?:$b['id']<=>$a['id']);
elseif($sort==='newest')usort($rows,fn($a,$b)=>$b['id']<=>$a['id']);
elseif($sort==='name')usort($rows,fn($a,$b)=>strnatcasecmp($a['nome'],$b['nome']));
$base=['q'=>$q,'filter'=>$filter,'owner'=>$owner,'sort'=>$sort];if($archived)$base['archived']='1';
?>
<div class="page-heading"><div><span class="eyebrow">RELACIONAMENTO QUE FLUI</span><h1><?=$archived?'Clientes arquivados':'Clientes'?></h1><p>Contatos, responsáveis e próximos passos em um só lugar.</p></div><div class="actions"><a class="button secondary" href="?view=import">Importar planilha</a><a class="button primary" href="?view=client-edit"><?=icon('plus')?> Novo cliente</a></div></div>
<section class="stats" aria-label="Resumo do acompanhamento"><a class="stat" href="index.php"><span>Clientes na carteira</span><div><strong><?=$allCount?></strong><?=icon('users')?></div><small>Visão de toda a equipe</small></a><a class="stat stat-amber" href="?filter=late"><span>Precisam de contato</span><div><strong><?=$stale?></strong><?=icon('clock')?></div><small>Conforme a frequência de cada cliente</small></a><a class="stat" href="?filter=due"><span>Próximos contatos vencidos</span><div><strong><?=$lateCount?></strong><?=icon('calendar')?></div><small>Datas de retorno pendentes</small></a><a class="stat" href="?view=tasks"><span>Minhas subtarefas abertas</span><div><strong><?=$mine?></strong><?=icon('tasks')?></div><small>Seus próximos passos</small></a></section>
<div class="view-toolbar"><div class="view-tabs" aria-label="Visualização"><a class="<?=$layout==='list'?'selected':''?>" href="?<?=h(http_build_query($base+['layout'=>'list']))?>"><?=icon('tasks')?> Lista</a><a class="<?=$layout==='cards'?'selected':''?>" href="?<?=h(http_build_query($base+['layout'=>'cards']))?>"><?=icon('grid')?> Cards</a><a class="<?=$layout==='board'?'selected':''?>" href="?<?=h(http_build_query($base+['layout'=>'board']))?>"><?=icon('board')?> Quadro</a></div><?php if($admin):?><a class="muted-link" href="?view=statuses">Gerenciar status</a><?php endif;?><span class="results-count"><?=count($rows)?> <?=count($rows)===1?'cliente':'clientes'?></span></div>
<form method="get" class="filters" role="search"><input type="hidden" name="layout" value="<?=h($layout)?>"><?php if($archived):?><input type="hidden" name="archived" value="1"><?php endif;?><label class="search-field"><?=icon('search')?><span class="sr-only">Buscar cliente</span><input type="search" name="q" value="<?=h($q)?>" placeholder="Buscar por nome ou ID" maxlength="160"></label><label><span class="sr-only">Filtrar status</span><select name="filter"><option value="">Todos os status</option><?php options(['late'=>'Precisam de contato','due'=>'Retornos vencidos']+statusLabels(),$filter);?></select></label><label><span class="sr-only">Responsável do CS</span><select name="owner"><option value="">Toda a equipe</option><?php foreach($users as $u):?><option value="<?=(int)$u['id']?>" <?=$owner===(string)$u['id']?'selected':''?>><?=h($u['nome'])?></option><?php endforeach;?></select></label><label><span class="sr-only">Ordenar clientes</span><select name="sort"><?php options(['oldest'=>'Sem contato há mais tempo','updated'=>'Atualizados recentemente','newest'=>'Clientes mais novos','name'=>'Nome do cliente'],$sort);?></select></label><button class="button secondary">Filtrar</button><?php if($q||$filter||$owner):?><a href="index.php" class="clear-filter">Limpar</a><?php endif;?></form>
<div id="client-results"><?php if(!$allCount):?><section class="empty-state"><span class="empty-symbol"><?=icon('users')?></span><h2><?=$archived?'Nenhum cliente arquivado':'Nenhum cliente cadastrado'?></h2><p><?=$archived?'Os acompanhamentos arquivados ficam disponíveis para consulta.':'Cadastre um cliente ou importe uma planilha.'?></p><?php if(!$archived):?><a class="button primary" href="?view=client-edit">Adicionar cliente</a><a class="button secondary" href="?view=technicians">Ver contatos</a><?php endif;?></section>
<?php elseif(!$rows):?><section class="empty-state"><span class="empty-symbol"><?=icon('search')?></span><h2>Nenhum cliente encontrado</h2><p>Ajuste os filtros ou procure outro nome.</p><a href="index.php" class="button secondary">Limpar filtros</a></section>
<?php elseif($layout==='list'):require __DIR__.'/client-list.php';?>
<?php elseif($layout==='board'):?><p class="board-hint muted"><?=$archived?'Acompanhamentos arquivados.':'Arraste um card entre as colunas ou use o seletor de status de cada card.'?></p><div class="kanban"><?php foreach(statusLabels() as $status=>$label):$column=array_filter($rows,fn($c)=>clientStage($c)===$status);?><section class="kanban-column" data-status="<?=h($status)?>"><h2><span class="status-dot <?=h(stageClass($status))?>"></span><?=h($label)?><span><?=count($column)?></span></h2><a class="column-list-link" href="?<?=h(http_build_query(array_merge($base,['layout'=>'list','filter'=>$status])))?>"><?=icon('tasks')?> Ver em lista</a><?php if($admin):?><a class="column-delete-link text-danger" href="?view=statuses&amp;delete=<?=h($status)?>">Excluir seção</a><?php endif;?><div class="kanban-cards"><?php foreach($column as $c)clientCard($c,!$archived);?><?php if(!$column):?><p class="column-empty">Nenhum cliente nesta etapa</p><?php endif;?></div></section><?php endforeach;?></div>
<?php else:?><div class="client-grid"><?php foreach($rows as $c)clientCard($c);?></div><?php endif;?>

</div>
