<?php
$id=positiveId($_GET['client']);$c=client($id);if($c['deletedAt']&&!$admin)throw new DomainException('Cliente não encontrado.');
$last=sql("SELECT * FROM updates WHERE clientId=? AND kind='contact' ORDER BY contactAt DESC,id DESC LIMIT 1",[$id])->fetch()?:[];
$c['contactAt']=$last['contactAt']??null;$owner=$c['ownerId']?sql('SELECT nome FROM users WHERE id=?',[$c['ownerId']])->fetchColumn():null;
$techs=sql('SELECT t.* FROM technicians t JOIN client_technicians ct ON ct.technicianId=t.id WHERE ct.clientId=? AND t.deletedAt IS NULL ORDER BY t.nome',[$id])->fetchAll();
$tasks=sql('SELECT t.*,u.nome AS assigneeName FROM tasks t LEFT JOIN users u ON u.id=t.assigneeId WHERE t.clientId=? AND t.deletedAt IS NULL ORDER BY (t.completedAt IS NOT NULL), (t.dueDate IS NULL),t.dueDate,t.id',[$id])->fetchAll();
$done=count(array_filter($tasks,fn($t)=>$t['completedAt']!==null));$feedFilter=in_array($_GET['feed']??'all',['all','contact','comment'],true)?($_GET['feed']??'all'):'all';
$feed=sql('SELECT * FROM updates WHERE clientId=?'.($feedFilter==='all'?'':' AND kind=?').' ORDER BY createdAt DESC,id DESC',$feedFilter==='all'?[$id]:[$id,$feedFilter])->fetchAll();
$lastUpdate=sql('SELECT * FROM updates WHERE clientId=? ORDER BY createdAt DESC,id DESC LIMIT 1',[$id])->fetch();
?>
<div class="detail-nav"><a href="index.php" class="back-link"><?=icon('arrow')?> Clientes</a><span>/</span><span>#<?=$id?></span><div class="detail-actions"><?php if(!$c['deletedAt']):?><a href="?view=client-edit&amp;id=<?=$id?>" class="button secondary compact"><?=icon('edit')?> Editar</a><form method="post"><?php formAction('client_status',$c);?><input type="hidden" name="status" value="<?=$c['status']==='done'?'active':'done'?>"><button class="button <?=$c['status']==='done'?'secondary':'primary'?> compact"><?=icon('check')?><?=$c['status']==='done'?'Reabrir acompanhamento':'Concluir acompanhamento'?></button></form><?php endif;?></div></div>
<div class="detail-title"><span class="client-symbol large"><?=h(initials($c['nome']))?></span><div><span class="eyebrow">ACOMPANHAMENTO DO CLIENTE</span><h1><?=h($c['nome'])?></h1></div></div>
<?php if($c['deletedAt']):?><div class="notice">Cliente arquivado. Histórico preservado para consulta.</div><?php endif;?>
<?php followUpBanner($c);?><div class="detail-layout"><div class="detail-main"><section class="panel description-panel"><div class="section-heading"><h2>Descrição</h2><?php if(!$c['deletedAt']):?><a href="?view=client-edit&amp;id=<?=$id?>" class="muted-link">Editar descrição</a><?php endif;?></div><?php if($c['observacoes']):?><div class="description-text"><?=nl2br(h($c['observacoes']))?></div><?php else:?><p class="description-placeholder">Qual é o contexto deste cliente? Registre os objetivos e informações que a equipe precisa ter à mão.</p><?php endif;?></section>
<section class="panel" id="subtasks"><div class="section-heading"><h2><?=icon('tasks')?> Subtarefas <span class="count"><?=$done?>/<?=count($tasks)?></span></h2><?php if(!$c['deletedAt']):?><a href="?view=task&amp;client=<?=$id?>" class="text-button"><?=icon('plus')?> Adicionar</a><?php endif;?></div><?php if($tasks):?><progress class="task-progress" max="<?=count($tasks)?>" value="<?=$done?>" aria-label="Progresso das subtarefas"></progress><div class="tasks-list"><?php foreach($tasks as $t)taskRow($t,false,(bool)$c['deletedAt']);?></div><?php else:?><div class="inline-empty"><p>Nenhuma subtarefa por enquanto.</p><span>Divida o acompanhamento em ações com responsáveis e prazos.</span></div><?php endif;?></section>
<section class="panel activity-panel" id="activity"><div class="section-heading"><h2><?=icon('chat')?> Atualizações</h2><span class="muted">Mais recentes primeiro</span></div>
<?php if(!$c['deletedAt']):?><form method="post" class="composer"><?php formAction('update');?><input type="hidden" name="clientId" value="<?=$id?>"><input type="hidden" name="requestToken" value="<?=h(postVal('requestToken',bin2hex(random_bytes(32))))?>"><div class="composer-header"><?=avatar($user['nome'],(int)$user['id'],'xs')?><strong><?=h($user['nome'])?></strong><label><span class="sr-only">Tipo de atualização</span><select name="kind" id="update-kind"><option value="comment" <?=postVal('kind')!=='contact'?'selected':''?>>Comentário interno</option><option value="contact" <?=postVal('kind')==='contact'?'selected':''?>>Contato com cliente</option></select></label></div><label class="sr-only" for="message">Mensagem</label><textarea id="message" name="mensagem" rows="4" required maxlength="15000" placeholder="Compartilhe uma atualização ou registre o que foi combinado…"><?=h(postVal('mensagem'))?></textarea><div class="contact-fields" id="contact-fields"><label>Pessoa contatada<select name="technicianId"><option value="">Selecione</option><?php foreach($techs as $t):?><option value="<?=(int)$t['id']?>" <?=postVal('technicianId')==(string)$t['id']?'selected':''?>><?=h($t['nome'])?></option><?php endforeach;?></select></label><label>Data e hora do contato<input type="datetime-local" name="contactAt" value="<?=h(postVal('contactAt',date('Y-m-d\TH:i')))?>"></label></div><div class="composer-footer"><small id="composer-hint">Comentários internos não alteram a data do último contato.</small><button class="button primary compact">Publicar atualização</button></div></form><?php endif;?>
<nav class="feed-tabs" aria-label="Filtrar atualizações"><?php foreach(['all'=>'Todas','contact'=>'Contatos','comment'=>'Comentários'] as $key=>$label):?><a class="<?=$feedFilter===$key?'selected':''?>" href="?client=<?=$id?>&amp;feed=<?=$key?>#activity"><?=$label?></a><?php endforeach;?></nav>
<div class="activity-feed"><?php if(!$feed):?><div class="inline-empty"><p>Nenhuma atualização nesta categoria.</p></div><?php endif;?><?php foreach($feed as $entry):?>
<?php if($entry['kind']==='system'):?><article class="system-event"><span class="event-marker"></span><div><p><strong><?=h($entry['userNameAtTime'])?></strong> · <?=h($entry['mensagem'])?></p><time><?=h(stamp($entry['createdAt']))?></time></div></article>
<?php else:?><article class="comment"><?=avatar($entry['userNameAtTime'],(int)$entry['userId'],'xs')?><div class="comment-body"><div class="comment-top"><strong><?=h($entry['userNameAtTime'])?></strong><time><?=h(stamp($entry['createdAt']))?></time></div><?php if($entry['kind']==='contact'):?><div class="contact-event"><span class="pill contact-pill">Contato com cliente</span><span><?=h(stamp($entry['contactAt']))?> · <?=h($entry['technicianNameAtTime'])?></span></div><?php endif;?><p><?=nl2br(h($entry['mensagem']))?></p></div></article><?php endif;?>
<?php endforeach;?></div></section></div>
<aside class="detail-aside"><section class="panel properties"><h2>Detalhes do acompanhamento</h2><div class="property"><span>Responsável do CS</span><div class="owner-line"><?=avatar($owner?:null,(int)$c['ownerId'],'xs')?><strong><?=h($owner?:'Sem responsável')?></strong></div></div><div class="property technicians-property"><span>Contatos do cliente</span><div class="tech-chips"><?php foreach($techs as $t):?><div class="technician-contact-card"><strong><?=h($t['nome'])?></strong><?php technicianContacts($t);?></div><?php endforeach;?><?php if(!$techs):?><span class="muted">Sem contato ativo</span><?php endif;?></div></div><div class="property"><span>Status</span><span class="pill <?=h(stageClass(clientStage($c)))?>"><?=h(statusLabels()[clientStage($c)])?></span></div><div class="property"><span>Prioridade</span><span class="pill priority-<?=h($c['priority'])?>"><?=icon('flag')?><?=h(PRIORITIES[$c['priority']])?></span></div><div class="property"><span>Próximo contato</span><strong class="<?=late($c['nextContact'])&&$c['status']!=='done'?'text-danger':''?>"><?=icon('calendar')?><?=h(shortDate($c['nextContact']))?></strong></div><div class="property"><span>Frequência combinada</span><strong>A cada <?=(int)$c['cadence']?> dias</strong></div>
<div class="last-contact-box <?=contactLate($c)?'is-late':''?>"><?=icon('clock')?><span>Último contato</span><strong><?=h(contactLabel($c['contactAt']))?></strong><small><?=$c['contactAt']?h(stamp($c['contactAt'])):'Nenhum contato registrado'?></small><?php if($last):?><small>Contato: <?=h($last['technicianNameAtTime'])?></small><?php endif;?></div><div class="audit-note">Última atualização por <strong><?=h($lastUpdate['userNameAtTime']??'—')?></strong><br><?=h(stamp($lastUpdate['createdAt']??null))?></div></section>
<?php if($admin):?><form method="post" <?=$c['deletedAt']?'':'data-confirm="Arquivar este cliente? O histórico e as subtarefas serão preservados."'?>><?php formAction($c['deletedAt']?'client_restore':'client_archive',$c);?><button class="button secondary full"><?=icon('archive')?><?=$c['deletedAt']?'Restaurar cliente':'Arquivar cliente'?></button></form><?php endif;?></aside></div>
