<?php
$batch=$_SESSION['client_import']??null;
if($batch&&$batch['expires']<time()){unset($_SESSION['client_import']);$batch=null;}
$report=$_SESSION['import_result']??null;
?>
<div class="page-heading"><div><h1>Importar clientes</h1><p>Envie uma planilha, confira os dados e confirme a importação.</p></div><a href="index.php" class="button secondary">Voltar aos clientes</a></div>
<?php if($report):?><section class="panel"><h2>Resultado da última importação</h2><p><?=(int)$report['created']?> criado(s) · <?=(int)$report['skipped']?> ignorado(s)</p><details><summary>Ver resultado por linha</summary><div class="table-scroll"><table><thead><tr><th>Linha</th><th>Cliente</th><th>Resultado</th></tr></thead><tbody><?php foreach($report['items'] as $r):?><tr><td><?=(int)$r['line']?></td><td><?=h($r['name'])?></td><td><?=h($r['message'])?></td></tr><?php endforeach;?></tbody></table></div></details></section><?php endif;?>
<?php if($batch):?>
<section class="panel"><div class="section-heading"><h2>Conferir importação · <?=count($batch['rows'])?> linha(s)</h2></div><p>Os dados abaixo ainda não foram salvos. Campos inválidos aparecem nos avisos; os outros dados da linha serão importados.</p><p class="muted">Clientes começam em “<?=h(statusLabels()[defaultStage()])?>”, sem responsável do CS. Contato da planilha é uma pessoa do cliente, não um usuário do sistema. A frequência vazia usa 7 dias; a data vazia fica sem agendamento.</p>
<p><?=$batch['skipDuplicates']?'Nomes já cadastrados, inclusive arquivados, serão ignorados. Nomes repetidos neste arquivo criam apenas o primeiro cliente.':'Nomes repetidos serão cadastrados como clientes separados.'?></p>
<div class="table-scroll import-preview"><table><thead><tr><th>Linha</th><th>Cliente</th><th>Descrição</th><th>Contato</th><th>WhatsApp</th><th>E-mail</th><th>Dias</th><th>Próximo contato</th><th>Conferência</th></tr></thead><tbody><?php foreach($batch['rows'] as $r):?><tr><td><?=(int)$r['line']?></td><td><?=h($r['name']?:'—')?></td><td><div class="import-description"><?=h($r['description']?:'—')?></div></td><td><?=h($r['contact']?:'—')?></td><td><?=h($r['phone']?:'—')?></td><td><?=h($r['email']?:'—')?></td><td><?=(int)$r['cadence']?></td><td><?=h(shortDate($r['next']))?></td><td><?=h($r['skip']?:($r['duplicate']&&$batch['skipDuplicates']?'Nome já cadastrado; será ignorado.':($r['warnings']?implode(' ',$r['warnings']):'Pronto para importar.')))?></td></tr><?php endforeach;?></tbody></table></div>
<div class="actions import-actions"><form method="post" data-confirm="Confirmar a criação dos clientes desta prévia? Confira os avisos antes de continuar."><?php formAction('import_confirm');?><input type="hidden" name="requestToken" value="<?=h($batch['token'])?>"><button class="button primary">Confirmar importação</button></form><form method="post"><?php formAction('import_cancel');?><button class="button secondary">Descartar prévia</button></form></div></section>
<?php else:?>
<section class="panel narrow"><h2>Selecionar planilha</h2><form method="post" enctype="multipart/form-data" class="form-stack"><?php formAction('import_preview');?><input type="hidden" name="MAX_FILE_SIZE" value="1048576"><label>Arquivo Excel ou CSV<input type="file" name="spreadsheet" accept=".xlsx,.csv" required><small>Até 1 MB e 500 linhas. Excel: primeira aba. CSV: UTF-8, separado por ponto e vírgula, vírgula ou tabulação.</small></label><label class="check-label"><input type="checkbox" name="skipDuplicates" checked> Ignorar nomes de clientes já cadastrados</label><button class="button primary">Conferir planilha</button><a href="assets/modelo-clientes.csv" download>Baixar modelo CSV</a></form></section>
<section class="panel"><h2>Colunas da planilha</h2><div class="table-scroll"><table><thead><tr><th>Coluna</th><th>Como preencher</th></tr></thead><tbody><tr><td>nome_cliente</td><td>Nome do cliente. Sem ele, a linha é ignorada.</td></tr><tr><td>descricao</td><td>Descrição do acompanhamento (opcional).</td></tr><tr><td>tec_responsavel</td><td>Nome do contato do cliente (opcional).</td></tr><tr><td>whatsapp_responsavel</td><td>DDD e número; para outros países, + e código do país. Formate a célula como texto.</td></tr><tr><td>email_responsavel</td><td>E-mail do contato (opcional).</td></tr><tr><td>dias_de_contato</td><td>Inteiro de 1 a 365. Vazio: 7 dias.</td></tr><tr><td>prox_contato</td><td>Data do Excel, dd/mm/aaaa ou aaaa-mm-dd. Vazio: sem data.</td></tr></tbody></table></div><p class="muted">Campos vazios, null, nulo ou NaN são ignorados. Sem nome do contato, WhatsApp e e-mail não criam um contato anônimo. Cada linha cria um cliente e, se informado, um contato próprio. Não altera clientes existentes. Fórmulas não são calculadas: prefira colar somente valores antes de enviar.</p></section>
<?php endif;?>
