<?php
requireAdmin($user);$edit=isset($_GET['edit'])?stageRow(field($_GET,'edit',40)):null;
?>
<div class="page-heading"><div><span class="eyebrow">ORGANIZAÇÃO DA EQUIPE</span><h1>Status do quadro</h1><p>Crie as etapas do acompanhamento. Cada status aparece na Lista, nos Cards e no Quadro.</p></div><a class="button secondary" href="?layout=board">Abrir quadro</a></div>
<?php if(isset($_GET['delete'])):
$remove=stageRow(field($_GET,'delete',40));$destinations=statusLabels();unset($destinations[$remove['key']]);
$count=(int)sql('SELECT COUNT(*) FROM clients WHERE boardStatus=? OR (boardStatus IS NULL AND status=?)',[$remove['key'],$remove['key']])->fetchColumn();
$canRemove=count(array_filter(statusRows(),fn($r)=>(int)$r['isClosed']===(int)$remove['isClosed']))>1;
?><section class="panel section-removal"><h2>Excluir seção: <?=h($remove['label'])?></h2><p>Esta seção contém <?=$count?> cliente(s), incluindo arquivados. Os clientes, suas conversas e subtarefas serão mantidos.</p>
<?php if($canRemove):?><form method="post" action="?view=statuses" class="form-stack" data-confirm="Excluir esta seção e transferir todos os seus clientes para a seção escolhida? Nenhum cliente, conversa ou subtarefa será apagado."><?php formAction('stage_delete');?><input type="hidden" name="key" value="<?=h($remove['key'])?>"><label>Mover os clientes para<select name="target" required><option value="">Selecione outra seção</option><?php options($destinations,'');?></select></label><p class="muted">O status e os alertas seguem a seção de destino: uma seção concluída encerra o acompanhamento; uma seção em aberto o reativa.</p><div class="actions"><button class="button danger">Excluir seção e mover clientes</button><a class="button secondary" href="?view=statuses">Cancelar</a></div></form>
<?php else:?><p>Mantenha pelo menos uma seção em aberto e uma concluída. Crie outra seção do mesmo tipo antes de excluir esta.</p><a href="?view=statuses">Voltar</a><?php endif;?></section><?php endif;?>
<div class="admin-layout"><section class="panel"><h2>Etapas cadastradas</h2><div class="table-scroll"><table><thead><tr><th>Status</th><th>Ordem</th><th>Tipo</th><th>Ações</th></tr></thead><tbody><?php foreach(statusRows() as $s):?><tr><td><span class="pill stage-color-<?=h($s['color'])?>"><?=h($s['label'])?></span></td><td><?=(int)$s['sortOrder']?></td><td><?=$s['isClosed']?'Concluído':'Em aberto'?></td><td><div class="actions"><a href="?view=statuses&amp;edit=<?=h($s['key'])?>">Editar</a><a class="text-danger" href="?view=statuses&amp;delete=<?=h($s['key'])?>">Excluir seção</a></div></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel"><h2><?=$edit?'Editar status':'Novo status'?></h2><form method="post" class="form-stack"><?php formAction('stage_save');?><input type="hidden" name="key" value="<?=h($edit['key']??'')?>"><label>Nome<input name="label" required maxlength="60" value="<?=h(postVal('label',$edit['label']??''))?>" placeholder="Ex.: Aguardando instalação"></label><label>Cor<select name="color"><?php options(PALETTES,postVal('color',$edit['color']??'blue'));?></select></label><label>Ordem no quadro<input type="number" name="sortOrder" required min="0" max="9999" value="<?=h(postVal('sortOrder',$edit['sortOrder']??50))?>"><small>Números menores aparecem primeiro.</small></label><label class="check-label"><input type="checkbox" name="isClosed" value="1" <?=($_SERVER['REQUEST_METHOD']==='POST'?isset($_POST['isClosed']):!empty($edit['isClosed']))?'checked':''?> <?=!empty($edit['builtin'])?'disabled':''?>> Representa acompanhamento concluído</label><p class="muted">Etapas concluídas não geram alertas de contato. Os status originais mantêm seu tipo.</p><button class="button primary">Salvar status</button><?php if($edit):?><a href="?view=statuses">Cancelar edição</a><?php endif;?></form></section></div>
