<?php
$showDone=($_GET['completed']??'')==='1';
$tasks=sql('SELECT t.*,u.nome AS assigneeName,c.nome AS clientName FROM tasks t JOIN clients c ON c.id=t.clientId LEFT JOIN users u ON u.id=t.assigneeId WHERE t.deletedAt IS NULL AND c.deletedAt IS NULL'.($view==='tasks'?' AND t.assigneeId=?':'').($showDone?'':' AND t.completedAt IS NULL').' ORDER BY (t.completedAt IS NOT NULL),(t.dueDate IS NULL),t.dueDate,t.id',$view==='tasks'?[$user['id']]:[])->fetchAll();
?>
<div class="page-heading"><div><span class="eyebrow"><?=$view==='tasks'?'MEU TRABALHO':'PRÓXIMOS PASSOS DA EQUIPE'?></span><h1><?=$view==='tasks'?'Minhas tarefas':'Agenda'?></h1><p><?=$view==='tasks'?'O que está com você, organizado por prazo.':'Retornos e subtarefas para manter os clientes por perto.'?></p></div><form method="get"><input type="hidden" name="view" value="<?=h($view)?>"><label class="inline-check"><input type="checkbox" name="completed" value="1" <?=$showDone?'checked':''?>> Incluir subtarefas concluídas</label><button class="button secondary compact">Aplicar</button></form></div>
<?php if($view==='agenda'):$contacts=sql("SELECT c.*,u.nome AS ownerName FROM clients c LEFT JOIN users u ON u.id=c.ownerId WHERE c.deletedAt IS NULL AND c.status<>'done' AND c.nextContact IS NOT NULL ORDER BY c.nextContact,c.id")->fetchAll();?><section class="panel"><div class="section-heading"><h2><?=icon('chat')?> Próximos contatos <span class="count"><?=count($contacts)?></span></h2></div><?php foreach($contacts as $c):?><a class="agenda-contact" href="?client=<?=(int)$c['id']?>"><span class="date-tile <?=late($c['nextContact'])?'overdue':''?>"><strong><?=date('d',strtotime($c['nextContact']))?></strong><small><?=date('m/Y',strtotime($c['nextContact']))?></small></span><div><strong><?=h($c['nome'])?></strong><small><?=h($c['ownerName']?:'Sem responsável')?> · <?=h(statusLabels()[clientStage($c)])?></small></div><span class="pill <?=late($c['nextContact'])?'priority-urgent':'status-active'?>"><?=late($c['nextContact'])?'Atrasado':($c['nextContact']===date('Y-m-d')?'Hoje':shortDate($c['nextContact']))?></span><?=icon('chevron')?></a><?php endforeach;?><?php if(!$contacts):?><div class="inline-empty"><p>Nenhum retorno agendado.</p><span>Defina o próximo contato na edição de cada cliente.</span></div><?php endif;?></section><?php endif;?>
<?php
$groups=['overdue'=>['Prazos vencidos',[]],'today'=>['Hoje',[]],'upcoming'=>['Próximos dias',[]],'undated'=>['Sem prazo',[]],'done'=>['Concluídas',[]]];
foreach($tasks as $t){$key=$t['completedAt']?'done':(!$t['dueDate']?'undated':(late($t['dueDate'])?'overdue':($t['dueDate']===date('Y-m-d')?'today':'upcoming')));$groups[$key][1][]=$t;}
foreach($groups as $key=>[$label,$items]):if(!$items)continue;?><section class="panel"><div class="section-heading"><h2><?=icon('tasks')?><?=h($label)?><span class="count"><?=count($items)?></span></h2></div><div class="tasks-list"><?php foreach($items as $t)taskRow($t,true);?></div></section><?php endforeach;?>
<?php if(!$tasks):?><section class="empty-state small-empty"><span class="empty-symbol"><?=icon('check')?></span><h2><?=$showDone?'Nenhuma subtarefa encontrada':'Nenhuma subtarefa pendente'?></h2><p>Crie subtarefas dentro de um cliente e atribua um responsável.</p><a href="index.php" class="button secondary">Ver clientes</a></section><?php endif;?>
